fixup

diff --git a/builds/mac b/builds/mac
--- a/builds/mac
+++ b/builds/mac
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-COMPILED_AT='Mon Jan 18 14:10:33 PST 2016'
+COMPILED_AT='Mon Jan 18 17:31:30 PST 2016'
 #
 #  _           _        _ _  __           _
 # (_)_ __  ___| |_ __ _| | |/ _| ___  ___| |_
@@ -361,7 +361,7 @@ if [ "$OS_NUMBER" -lt "11" ]; then
 else
   inform "Skipping repair permissions, as this is disabled as of El Capitan." true
   inform "  Search for diskutil repairPermissions and System Integrity " true
-  inform "  Protection to learn more. "
+  inform "  Protection on Google to learn more. "
 fi
 
 
@@ -790,6 +790,11 @@ fi
 #-------------------------------------------------------------------------------
 
 inform "Setting Git configurations..." true
+echo ""
+
+read -p "Enter your Github Email: "      GITHUB_EMAIL
+read -p "Enter your (real) first name: " FNAME
+read -p "Enter your (real) last name: "  LNAME
 
 # https://www.kernel.org/pub/software/scm/git/docs/git-config.html
 git config --global user.name    "$fname $lname"
@@ -832,7 +837,8 @@ git config --global alias.set-deploy = "!git config --local alias.deploy \"subtr
 git config --global alias.co 'checkout'
 git config --global alias.bs 'branch -v'
 git config --global alias.rs 'remote -v'
-show "Complete!"
+
+show "Complete!" true
 
 #-------------------------------------------------------------------------------
 # Capture GitHub credentials (github_capture_credentials.sh)
@@ -840,18 +846,60 @@ show "Complete!"
 
 inform "Enter information to set up your GitHub configuration." true
 
-read -p "Enter your Github Username: "    github_name
-read -p "Enter your Github Email: "       github_email
-read -s -p "Enter your Github Password: " github_password
-echo ""
-read -p "Enter your (real) first name: "  fname
-read -p "Enter your (real) last name: "   lname
+function get_credentials() {
+  read -p  "Enter your Github Username: " GITHUB_NAME
+  read -sp "Enter your Github Password: " GITHUB_PASSWORD
+}
+
+# https://developer.github.com/v3/users/#get-the-authenticated-user
+function check_credentials() {
+  local UNAME="$1"
+  local PASS="$2"
+  curl https://api.github.com/user/keys \
+    -H "User-Agent: WDIInstallFest" \
+    -H "Accept: application/vnd.github.v3+json" \
+    -u "$UNAME:$PASS" \
+    2>/dev/null \
+    | ruby -e " \
+      json = JSON.parse(STDIN.gets)
+      if json.class == Array || json.key('id')
+        puts
+        puts('Authenticated!')
+        exit 0
+      else
+        puts
+        puts('Failed: ' + json.to_s)
+        exit 1
+      end
+    " -r JSON
+}
+
+CHECK_NOT_PASSED="true"
+COUNTER=1
+while [ $COUNTER -lt 4 ] && [ $CHECK_NOT_PASSED ]; do
+  get_credentials
+  check_credentials $GITHUB_NAME $GITHUB_PASSWORD
+  if [ $? -eq 0 ]; then
+    echo ""
+    CHECK_NOT_PASSED=""
+  else
+    echo ""
+    [ $COUNTER -lt 3 ] && echo "Please try again! $((3-$COUNTER)) chance(s) left... "
+    let COUNTER=COUNTER+1
+  fi
+done
+
+if [ $CHECK_NOT_PASSED ]; then
+  GITHUB_AUTHENTICATED=""
+  echo "Skipping GitHub authentication and SSH Key generation."
+else
+  GITHUB_AUTHENTICATED="true"
+fi
 
 show "Thank you!"
 
 #-------------------------------------------------------------------------------
-# Create and Upload SSH key. This script assumes jsawk is installed, and
-# must come after scripts/mac/homebrew_install_cli_apps. (github_add_ssh_key.sh)
+# Create and Upload SSH key for GitHub, if necessary. (github_add_ssh_key.sh)
 #-------------------------------------------------------------------------------
 
 # SSH keys establish a secure connection between your computer and GitHub
@@ -868,6 +916,54 @@ show "Thank you!"
 #   b. if there is another key, notify, warn, and suggest it be sent after.
 # 5. if there are no keys, then generate an id_rsa key and send.
 #   a. If sending fails, announce.
+
+
+if [ $GITHUB_AUTHENTICATED ]; then
+
+
+fi
+
+
+
+
+
+
+
+
+# curl https://api.github.com/user/keys \
+#   -H "User-Agent: WDIInstallFest" \
+#   -H "Accept: application/vnd.github.v3+json" \
+#   -u "hews:cLovesp15" \
+#   | ruby -e "json = JSON.parse(STDIN.gets);puts json" -r JSON
+
+#   jsawk -a 'return this[0]'
+
+# function get_profile() {
+#   local UNAME="$1"
+#   local PASS="$2"
+#   local DATA="$(curl https://api.github.com/user/keys         \
+#                   -H "User-Agent: WDIInstallfest"             \
+#                   -H "Accept: application/vnd.github.v3+json" \
+#                   -u "$UNAME:$PASS")"
+#   # jsawk is failing to parse json that is singular, ie begins with '{'
+#   # instead of '['… this ensures that singular results are given '[]'s
+#   if [[ $DATA =~ ^\[.*\]$ ]]; then
+#     echo "${DATA}"
+#   else
+#     echo "[${DATA}]"
+#   fi
+# }
+
+# function check_profile() {
+#   local UNAME="$1"
+#   local PASS="$2"
+#   local PROFID="$(get_profile $UNAME $PASS | jsawk -a 'return this[0].id')"
+#   if [ "$PROFID" ]; then
+#     return 0
+#   else
+#     return 1
+#   fi
+# }
 
 # SSH Keygen
 inform "Generating an SSH key to establish a secure connection " true
@@ -1439,4 +1535,5 @@ inform "We're done!" true
 echo "#-- fin -- #"
 
 fail "Please close your terminal and open a new one!" true
+echo ""
 
